### ISSUE TITLE
It would be nice if we could highlight/mark window hook functions

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-code-browser#10]
They take `WMWinHookStruct &s` as parameter.

**Comment by t-b** [comment]
And background functions, the most common ones take `WMBackgroundStruct &s`.

**Comment by ukos-git** [comment]
is `WMWinHookStruct`/`WMBackgroundStruct` the only parameter to that function or can there be more than this one?

**Comment by t-b** [comment]
- Both window hooks and background functions only take one parameter.
- From `DisplayHelpTopic "Named Window Hook Functions"` the function signature is always

```
Function MyWindowHook(s)
	STRUCT WMWinHookStruct &s
...
End
```
- From `DisplayHelpTopic "Background Task Example #1'` the easy ones have the signature

```
Function TestTask(s)
	STRUCT WMBackgroundStruct &s
...	
End
```

the more complicated ones have

```
Structure BackgroundStruct
	STRUCT WMBackgroundStruct wmbs
// other members
EndStructure

Function BkgFunc(s)
	STRUCT BackgroundStruct &s
End
```

from the help

```
You may also specify a user function that takes a user-defined STRUCT as long as the first elements of the structure match the WMBackgroundStruct or, preferably, if the first element is an instance of WMBackgroundStruct
```

It is okay to not support the complicated ones for now.

**Comment by ukos-git** [comment]
I only check the first parameter, if it matches to a pass-by-ref struct and then I only search for the first line following the function definition and match the name of the struct definition against `WMWinHookStruct`, `WMBackgroundStruct` and additionally to any other `WM[^\s,]Struct`

**Comment by ukos-git** [comment]
could be extended to search until a match occurs or end of function is encountered but this should suffice 99% of the functions.
