### ISSUE TITLE
Add Menu, GraphMarquee, SubMenu, ... entries to the list

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-code-browser#2]

**Comment by ukos-git** [comment]
The subTypes like for example `Table` are still recognized and categorized with a `windowMarker`. Not through subTypeList, though.

**Comment by t-b** [comment]
Sorry I think I'm not following where you are getting at.

**Comment by ukos-git** [comment]
I will collect all non-functional ws changes in a separate pr https://github.com/byte-physics/igor-code-browser/pull/18
