### ISSUE TITLE
loading non-existing procedures

### ISSUE THREAD

**Issue by ukos-git** [byte-physics/igor-code-browser#24]
When selecting a procedure, loaded from `User procedures` (using `include "MIES_include"`), the procedure location is saved when CodeBrowser is closed and restored when codebrowser is opened again the next time.

If this procedure is not loaded in current scope (i.e. in a new experiment), a procedure named `ProcGlobal#_error_` is tried to load

debug Output

```console
  existsPanel(...): panel does not exist
  generateModuleList(...): called
  generateModuleList(...): called
  generateProcedureList(...): called
  generateProcedureList(...): called
  existsPanel(...): panel exists
  initializePanel(...): called
  initializePanel(...): Error: SetIgorOption recreateListboxHScroll returned 3
  initializePanel(...): AfterCompiledHook: CodeBrowserModule#updatePanel;
  updatePanel(...): All Procedures were marked for parsing
  existsPanel(...): panel exists
  generateModuleList(...): called
  generateProcedureList(...): called
  getSaveRow(...): Element not found
  saveLoad(...): save state not found
  updateListBoxHook(...): parsing Procedure
  parseProcedure(...): CheckSum needs to be calculated
  addDecoratedFunctions(...): decl rows=0
  addDecoratedStructure(...): no Content in Procedure _error_
  setParsingTime(...): parsing time:2238.3
  saveResults(...): saving Results for ProcGlobal#_error_
  saveResults(...): Function list is not complete
```

We can not know, what procedure windows will be there when CodeBrowser loads the next time.
Maybe a (fixed length) Hash of the procedure name should be saved in preferences struct and compared to the Hash of the Procedure that is to be reloaded to ensure that the restored procedure is actually the same as the one saved.  If the procedure can not be found in the current environment, fall back to `ProcGlobal#Procedure`

**Comment by ukos-git** [comment]
related:

https://github.com/byte-physics/igor-code-browser/blob/662a43b07475f5c86f2266dec66731a932cf68c0/procedures/CodeBrowser_gui.ipf#L252

**Comment by t-b** [comment]
@ukos-git How about teaching showCode to ignore procedures named/matching "_error_"? And a constant for that would be nice as well.
