### ISSUE TITLE
crash at panelHook windowName

### ISSUE THREAD

**Issue by ukos-git** [byte-physics/igor-code-browser#27]
The panelHook sometimes does not get the windowName of the panel right. I think this is a problem upstream at resizePanel.

I have seen it in CodeBrowser multiple times when trying to re-build the panel. CodeBrowser is left in a non-functional state until IP is closed and re-opened again.

![panelhook-panelname](https://user-images.githubusercontent.com/16167358/49806471-2553d300-fd58-11e8-9e5d-01a30ef40670.PNG)

**Comment by t-b** [comment]
@ukos-git Reproduction recipe?

**Comment by ukos-git** [comment]
work hard on code --> error plops up and annoys me.

**Comment by t-b** [comment]
The call chain does not make sense. We call `ResizeControlsHook` from panelHook so we should see that function in there as well. Try upgrading to the latest nightly from http://www.wavemetrics.net/Downloads/latest8/.

**Comment by ukos-git** [comment]
It is already the latest version. I look into the error more closely next time.

**Comment by ukos-git** [comment]
![panelhook-panelname-v3](https://user-images.githubusercontent.com/16167358/49953695-f4fa6900-fefe-11e8-8113-4b14dc42470c.PNG)

**Comment by t-b** [comment]
So it is reproducible now?

**Comment by ukos-git** [comment]
No. Seems to happen when CodeBrowser is closed while in uncompiled state.

**Comment by t-b** [comment]
Emailed WM support as I could get Igor crashed.

**Comment by ukos-git** [comment]
Seems to be fixed upstream now. I have not encountered this bug again.

**Comment by t-b** [comment]
Good! Closing for now.
