### ISSUE TITLE
CodeBrowser lines get sometimes out of sync

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-code-browser#3]
Sometimes the line numbers which are the jump targets if clicking into the codebrowser are wrong. This might also be an Igor bug wrt to the after compile hook usage.

**Comment by ukos-git** [comment]
I also experience this sometimes and was thinking that this is due to git rebases. But I am not sure.

**Comment by ukos-git** [comment]
not sure. I'll address it as soon as I encounter it. I think it should be a rebase to an uncompilable commit or something similar.

**Comment by t-b** [comment]
This sould be fixed with #58.
