### ISSUE TITLE
cb display on windows 10

### ISSUE THREAD

**Issue by ukos-git** [byte-physics/igor-code-browser#45]
I just noticed that the display of list1 is not properly aligned for windows10. I suggest no left, right and bottom spaces between the listbox and the window.
<img width="309" alt="capture" src="https://user-images.githubusercontent.com/16167358/51686832-77dc0c80-1ff1-11e9-9162-49342f61544e.PNG">

**Comment by t-b** [comment]
Yeah I think making the panel really pleasant to view needs to be done at some point.

**Comment by ukos-git** [comment]
I was designing it on windows7 but windows10 should be the reference here.
