### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by ukos-git** [byte-physics/igor-code-browser#50]
Sometimes I find IP in uncompiled state and I am locally using this code to work around this

```igor
#pragma IndependentModule=COMPILE

Menu "CodeBrowser"
	"Compile/1", /Q, COMPILE#compile()
End

Function compile()
	execute/p/z/q "COMPILEPROCEDURES "
end
```

It is basically adding another Keyboard shortcut in an independent module so that it can always be called even if IP is in uncompiled state.

Is this something we could add to core CB or is it extending CB too far. The way I see CB is as a dev tool where this comes in handy.

**Comment by t-b** [comment]
Hmm. Well I think it would be handy if the codebrowser panel, on activation, checks if it is compiled or not, and if it is not compiled we try compiling. This would be handy and not adding a new shortcut.
